'use client';

import { useState, useEffect, useCallback, useReducer, useRef } from 'react';
import { ResponsiveLayout } from "@/components/layout/responsive-layout";
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { toast } from 'sonner';
import { createClient } from '@/lib/supabase/client';
import {
  Loader2,
  Save,
  RotateCcw,
  Eye,
  Printer,
  FileText,
  GraduationCap,
  Award,
  Settings,
  AlertCircle,
  CheckCircle,
  ChevronRight,
  User,
  Users,
  BookOpen,
  BarChart3,
  Trophy,
  Calendar,
  Hash,
  Image as ImageIcon,
  MapPin,
  Phone
} from 'lucide-react';

const supabase = createClient();

// ============================================
// TYPES
// ============================================

interface TabulationSettings {
  show_serial: boolean;
  show_roll: boolean;
  show_admission_no: boolean;
  show_father_name: boolean;
  show_mother_name: boolean;
  show_remarks: boolean;
  show_class_rank: boolean;
  show_section_rank: boolean;
  paper_size: 'A4' | 'Letter' | 'Legal';
  orientation: 'portrait' | 'landscape';
  font_size: 'small' | 'normal' | 'large';
  show_photo: boolean;
  show_total_marks: boolean;
  show_percentage: boolean;
}

interface ProgressCardSettings {
  show_photo: boolean;
  show_signature: boolean;
  show_seal: boolean;
  include_all_terms: boolean;
  paper_size: 'A4' | 'Letter' | 'Legal';
  orientation: 'portrait' | 'landscape';
  show_grade_distribution: boolean;
  show_attendance_summary: boolean;
  show_rank: boolean;
  show_address: boolean;
  show_parent_contact: boolean;
  show_dob: boolean;
  show_admission_date: boolean;
}

interface CertificateSettings {
  paper_size: 'A4' | 'Letter' | 'Legal';
  orientation: 'portrait' | 'landscape';
  show_border: boolean;
  border_color: string;
  border_width: number;
  background_pattern: boolean;
  font_family: 'default' | 'serif' | 'handwriting';
  show_seal: boolean;
  show_signature: boolean;
  show_achievement_details: boolean;
  show_date: boolean;
}

interface CommonSettings {
  header_text: string;
  footer_text: string;
  logo_position: 'left' | 'center' | 'right';
  watermark_enabled: boolean;
  watermark_text: string;
  primary_color: string;
  secondary_color: string;
  school_name_override: string | null;
  school_address_override: string | null;
  show_generated_date: boolean;
  show_page_numbers: boolean;
  show_qr_code: boolean;
}

interface PrintSettings {
  tabulation: TabulationSettings;
  progress_card: ProgressCardSettings;
  certificate: CertificateSettings;
  common: CommonSettings;
}

// ============================================
// DEFAULT SETTINGS
// ============================================

const DEFAULT_SETTINGS: PrintSettings = {
  tabulation: {
    show_serial: true,
    show_roll: true,
    show_admission_no: false,
    show_father_name: true,
    show_mother_name: false,
    show_remarks: false,
    show_class_rank: true,
    show_section_rank: true,
    paper_size: 'A4',
    orientation: 'landscape',
    font_size: 'normal',
    show_photo: true,
    show_total_marks: true,
    show_percentage: true
  },
  progress_card: {
    show_photo: true,
    show_signature: true,
    show_seal: true,
    include_all_terms: false,
    paper_size: 'A4',
    orientation: 'portrait',
    show_grade_distribution: true,
    show_attendance_summary: true,
    show_rank: true,
    show_address: false,
    show_parent_contact: true,
    show_dob: true,
    show_admission_date: false
  },
  certificate: {
    paper_size: 'A4',
    orientation: 'portrait',
    show_border: true,
    border_color: '#2563eb',
    border_width: 2,
    background_pattern: false,
    font_family: 'default',
    show_seal: true,
    show_signature: true,
    show_achievement_details: true,
    show_date: true
  },
  common: {
    header_text: '',
    footer_text: 'Generated by Kindergarten ERP',
    logo_position: 'left',
    watermark_enabled: false,
    watermark_text: 'কিন্ডারগার্টেন ইআরপি',
    primary_color: '#4f46e5',
    secondary_color: '#7c3aed',
    school_name_override: null,
    school_address_override: null,
    show_generated_date: true,
    show_page_numbers: true,
    show_qr_code: false
  }
};

// ============================================
// STATE REDUCER
// ============================================

type PrintSettingsAction = 
  | { type: 'SET_LOADING'; payload: boolean }
  | { type: 'SET_SAVING'; payload: boolean }
  | { type: 'SET_SETTINGS'; payload: PrintSettings }
  | { type: 'UPDATE_TABULATION'; key: keyof TabulationSettings; value: any }
  | { type: 'UPDATE_PROGRESS_CARD'; key: keyof ProgressCardSettings; value: any }
  | { type: 'UPDATE_CERTIFICATE'; key: keyof CertificateSettings; value: any }
  | { type: 'UPDATE_COMMON'; key: keyof CommonSettings; value: any }
  | { type: 'RESET' }
  | { type: 'SET_ACADEMIC_YEAR_ID'; payload: string | null }
  | { type: 'SET_SCHOOL_INFO'; payload: any };

interface PrintSettingsState {
  loading: boolean;
  saving: boolean;
  settings: PrintSettings;
  isDirty: boolean;
  academicYearId: string | null;
  schoolInfo: any;
}

const initialState: PrintSettingsState = {
  loading: true,
  saving: false,
  settings: DEFAULT_SETTINGS,
  isDirty: false,
  academicYearId: null,
  schoolInfo: null
};

function printSettingsReducer(state: PrintSettingsState, action: PrintSettingsAction): PrintSettingsState {
  switch (action.type) {
    case 'SET_LOADING':
      return { ...state, loading: action.payload };
    case 'SET_SAVING':
      return { ...state, saving: action.payload };
    case 'SET_SETTINGS':
      return { ...state, settings: action.payload, isDirty: false };
    case 'SET_ACADEMIC_YEAR_ID':
      return { ...state, academicYearId: action.payload };
    case 'SET_SCHOOL_INFO':
      return { ...state, schoolInfo: action.payload };
    case 'UPDATE_TABULATION':
      return {
        ...state,
        settings: {
          ...state.settings,
          tabulation: { ...state.settings.tabulation, [action.key]: action.value }
        },
        isDirty: true
      };
    case 'UPDATE_PROGRESS_CARD':
      return {
        ...state,
        settings: {
          ...state.settings,
          progress_card: { ...state.settings.progress_card, [action.key]: action.value }
        },
        isDirty: true
      };
    case 'UPDATE_CERTIFICATE':
      return {
        ...state,
        settings: {
          ...state.settings,
          certificate: { ...state.settings.certificate, [action.key]: action.value }
        },
        isDirty: true
      };
    case 'UPDATE_COMMON':
      return {
        ...state,
        settings: {
          ...state.settings,
          common: { ...state.settings.common, [action.key]: action.value }
        },
        isDirty: true
      };
    case 'RESET':
      return { ...state, settings: DEFAULT_SETTINGS, isDirty: true };
    default:
      return state;
  }
}

// ============================================
// REUSABLE COMPONENTS
// ============================================

interface ColorCodedSwitchProps {
  label: string;
  description: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  color: 'blue' | 'green' | 'purple' | 'amber' | 'orange' | 'teal' | 'pink' | 'gray';
  icon?: React.ReactNode;
  isFixed?: boolean;
}

const colorClasses = {
  blue: {
    bg: 'bg-blue-50 dark:bg-blue-950/30',
    border: 'border-blue-200 dark:border-blue-800',
    text: 'text-blue-700 dark:text-blue-300',
    desc: 'text-blue-600 dark:text-blue-400',
    switch: 'data-[state=checked]:bg-blue-600',
  },
  green: {
    bg: 'bg-green-50 dark:bg-green-950/30',
    border: 'border-green-200 dark:border-green-800',
    text: 'text-green-700 dark:text-green-300',
    desc: 'text-green-600 dark:text-green-400',
    switch: 'data-[state=checked]:bg-green-600',
  },
  purple: {
    bg: 'bg-purple-50 dark:bg-purple-950/30',
    border: 'border-purple-200 dark:border-purple-800',
    text: 'text-purple-700 dark:text-purple-300',
    desc: 'text-purple-600 dark:text-purple-400',
    switch: 'data-[state=checked]:bg-purple-600',
  },
  amber: {
    bg: 'bg-amber-50 dark:bg-amber-950/30',
    border: 'border-amber-200 dark:border-amber-800',
    text: 'text-amber-700 dark:text-amber-300',
    desc: 'text-amber-600 dark:text-amber-400',
    switch: 'data-[state=checked]:bg-amber-600',
  },
  orange: {
    bg: 'bg-orange-50 dark:bg-orange-950/30',
    border: 'border-orange-200 dark:border-orange-800',
    text: 'text-orange-700 dark:text-orange-300',
    desc: 'text-orange-600 dark:text-orange-400',
    switch: 'data-[state=checked]:bg-orange-600',
  },
  teal: {
    bg: 'bg-teal-50 dark:bg-teal-950/30',
    border: 'border-teal-200 dark:border-teal-800',
    text: 'text-teal-700 dark:text-teal-300',
    desc: 'text-teal-600 dark:text-teal-400',
    switch: 'data-[state=checked]:bg-teal-600',
  },
  pink: {
    bg: 'bg-pink-50 dark:bg-pink-950/30',
    border: 'border-pink-200 dark:border-pink-800',
    text: 'text-pink-700 dark:text-pink-300',
    desc: 'text-pink-600 dark:text-pink-400',
    switch: 'data-[state=checked]:bg-pink-600',
  },
  gray: {
    bg: 'bg-gray-50 dark:bg-gray-800/50',
    border: 'border-gray-200 dark:border-gray-700',
    text: 'text-gray-700 dark:text-gray-300',
    desc: 'text-gray-500 dark:text-gray-400',
    switch: 'data-[state=checked]:bg-gray-600',
  }
};

function ColorCodedSwitch({ label, description, checked, onChange, color, icon, isFixed = false }: ColorCodedSwitchProps) {
  const styles = colorClasses[color];
  
  return (
    <div className={`rounded-lg border ${styles.border} ${styles.bg} p-3 transition-all hover:shadow-sm`}>
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 flex-1">
          {icon && <div className={`${styles.text} flex-shrink-0`}>{icon}</div>}
          <div className="flex-1">
            <span className={`text-sm font-medium ${styles.text}`}>{label}</span>
            <p className={`text-xs ${styles.desc} mt-0.5`}>{description}</p>
          </div>
        </div>
        {isFixed ? (
          <div className="flex items-center gap-1 flex-shrink-0 ml-2">
            <div className="h-4 w-4 rounded-full bg-gray-300 dark:bg-gray-600"></div>
            <span className="text-xs text-gray-500 dark:text-gray-400 ml-1">Fixed</span>
          </div>
        ) : (
          <div className="flex items-center gap-2 flex-shrink-0 ml-3">
            <span className={`text-xs font-medium ${checked ? 'text-green-600 dark:text-green-400' : 'text-gray-400 dark:text-gray-500'}`}>
              {checked ? 'ON' : 'OFF'}
            </span>
            <Switch 
              checked={checked} 
              onCheckedChange={onChange} 
              className={`${styles.switch} ${!checked ? 'bg-gray-300 dark:bg-gray-700' : ''}`}
            />
          </div>
        )}
      </div>
    </div>
  );
}

function DirtyIndicator({ isDirty }: { isDirty: boolean }) {
  if (!isDirty) return null;
  return (
    <div className="flex items-center gap-1.5 px-2 py-1 bg-yellow-100 dark:bg-yellow-900/30 rounded-full">
      <AlertCircle className="h-3.5 w-3.5 text-yellow-600 dark:text-yellow-400" />
      <span className="text-xs text-yellow-700 dark:text-yellow-400">Unsaved changes</span>
    </div>
  );
}

// ============================================
// MAIN COMPONENT
// ============================================

export default function PrintSettingsPage() {
  const [state, dispatch] = useReducer(printSettingsReducer, initialState);
  const [activeTab, setActiveTab] = useState('tabulation');
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    loadData();
  }, []);

  useEffect(() => {
    if (state.isDirty && saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
    }
    if (state.isDirty) {
      saveTimeoutRef.current = setTimeout(() => {
        if (state.isDirty) {
          saveSettings(true);
        }
      }, 10000);
    }
    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
    };
  }, [state.settings, state.isDirty]);

  const loadData = async () => {
    dispatch({ type: 'SET_LOADING', payload: true });
    try {
      // ============================================
      // IMPROVED: Better academic year loading logic
      // ============================================
      console.log('Loading academic years...');
      
      // First, try to get the current academic year (is_current = true)
      let { data: currentYear, error: currentError } = await supabase
        .from('academic_years')
        .select('id, year_name, is_current, is_active, start_date, end_date')
        .eq('is_current', true)
        .maybeSingle();

      let academicYearId = null;
      let academicYearData = null;

      if (currentYear && !currentError) {
        console.log('Found current academic year:', currentYear);
        academicYearId = currentYear.id;
        academicYearData = currentYear;
      } else {
        // If no current year, try to get active year
        console.log('No current year found, looking for active year...');
        let { data: activeYear, error: activeError } = await supabase
          .from('academic_years')
          .select('id, year_name, is_current, is_active, start_date, end_date')
          .eq('is_active', true)
          .maybeSingle();

        if (activeYear && !activeError) {
          console.log('Found active academic year:', activeYear);
          academicYearId = activeYear.id;
          academicYearData = activeYear;
        } else {
          // If no active year, get any year (order by created_at or start_date)
          console.log('No active year found, getting any academic year...');
          let { data: anyYear, error: anyError } = await supabase
            .from('academic_years')
            .select('id, year_name, is_current, is_active, start_date, end_date')
            .order('created_at', { ascending: false })
            .limit(1)
            .maybeSingle();

          if (anyYear && !anyError) {
            console.log('Found any academic year:', anyYear);
            academicYearId = anyYear.id;
            academicYearData = anyYear;
            toast.warning(`No active academic year found. Using "${anyYear.year_name}" as default.`);
          } else {
            // Last resort: Try to get any record without filter
            console.log('Trying to get any academic year record...');
            const { data: fallbackYear, error: fallbackError } = await supabase
              .from('academic_years')
              .select('id, year_name')
              .limit(1)
              .maybeSingle();
            
            if (fallbackYear && !fallbackError) {
              console.log('Found fallback academic year:', fallbackYear);
              academicYearId = fallbackYear.id;
              toast.warning(`Using "${fallbackYear.year_name}" as academic year. Please set an active year in settings.`);
            } else {
              console.error('No academic years found in database:', fallbackError);
              toast.error('No academic year found. Please create an academic year first.');
            }
          }
        }
      }

      if (academicYearId) {
        console.log('Selected academic year ID:', academicYearId);
        dispatch({ type: 'SET_ACADEMIC_YEAR_ID', payload: academicYearId });
      }

      // Load school info
      const { data: schoolData } = await supabase
        .from('school_settings')
        .select('school_name, school_address, school_phone, school_email, school_logo')
        .limit(1)
        .maybeSingle();
      
      if (schoolData) {
        dispatch({ type: 'SET_SCHOOL_INFO', payload: schoolData });
      }

      // Load print settings
      if (academicYearId) {
        console.log('Loading print settings for academic year:', academicYearId);
        const { data, error } = await supabase
          .from('exam_settings_new')
          .select('setting_value')
          .eq('setting_key', 'print_settings')
          .eq('academic_year_id', academicYearId)
          .maybeSingle();

        if (error && error.code !== 'PGRST116') {
          console.error('Error loading settings:', error);
        }
        
        if (data?.setting_value) {
          const loadedSettings = data.setting_value;
          const mergedSettings: PrintSettings = {
            tabulation: { ...DEFAULT_SETTINGS.tabulation, ...loadedSettings.tabulation },
            progress_card: { ...DEFAULT_SETTINGS.progress_card, ...loadedSettings.progress_card },
            certificate: { ...DEFAULT_SETTINGS.certificate, ...loadedSettings.certificate },
            common: { ...DEFAULT_SETTINGS.common, ...loadedSettings.common }
          };
          dispatch({ type: 'SET_SETTINGS', payload: mergedSettings });
          console.log('Settings loaded successfully');
        } else {
          console.log('No existing settings found, using defaults');
        }
      }
    } catch (error) {
      console.error('Error in loadData:', error);
      toast.error('Failed to load settings');
    } finally {
      dispatch({ type: 'SET_LOADING', payload: false });
    }
  };

  const saveSettings = async (silent: boolean = false) => {
    if (!state.academicYearId) {
      toast.error('No academic year found. Please create an academic year first.');
      return;
    }

    dispatch({ type: 'SET_SAVING', payload: true });
    
    if (!silent) {
      toast.loading('Saving settings...', { id: 'save-settings' });
    }

    try {
      const { error } = await supabase
        .from('exam_settings_new')
        .upsert({
          academic_year_id: state.academicYearId,
          setting_key: 'print_settings',
          setting_value: state.settings,
          description: 'Global print settings for all reports',
          updated_at: new Date().toISOString()
        }, {
          onConflict: 'academic_year_id, setting_key'
        });

      if (error) throw error;

      if (!silent) {
        toast.success('Settings saved successfully', { id: 'save-settings' });
      }
    } catch (error) {
      console.error('Error saving settings:', error);
      if (!silent) {
        toast.error('Failed to save settings', { id: 'save-settings' });
      }
    } finally {
      dispatch({ type: 'SET_SAVING', payload: false });
    }
  };

  const resetToDefault = () => {
    dispatch({ type: 'RESET' });
    toast.info('Settings reset to default. Click Save to apply changes.');
  };

  // Type-safe update handlers
  const updateTabulation = useCallback((key: keyof TabulationSettings, value: TabulationSettings[keyof TabulationSettings]) => {
    dispatch({ type: 'UPDATE_TABULATION', key, value });
  }, []);

  const updateProgressCard = useCallback((key: keyof ProgressCardSettings, value: ProgressCardSettings[keyof ProgressCardSettings]) => {
    dispatch({ type: 'UPDATE_PROGRESS_CARD', key, value });
  }, []);

  const updateCertificate = useCallback((key: keyof CertificateSettings, value: CertificateSettings[keyof CertificateSettings]) => {
    dispatch({ type: 'UPDATE_CERTIFICATE', key, value });
  }, []);

  const updateCommon = useCallback((key: keyof CommonSettings, value: CommonSettings[keyof CommonSettings]) => {
    dispatch({ type: 'UPDATE_COMMON', key, value });
  }, []);

  if (state.loading) {
    return (
      <ResponsiveLayout>
        <div className="flex items-center justify-center min-h-[60vh]">
          <Loader2 className="h-8 w-8 animate-spin text-indigo-600" />
        </div>
      </ResponsiveLayout>
    );
  }

  // Calculate column count for preview
  const tabulationColumnCount = 
    (state.settings.tabulation.show_serial ? 1 : 0) +
    (state.settings.tabulation.show_photo ? 1 : 0) +
    (state.settings.tabulation.show_roll ? 1 : 0) +
    (state.settings.tabulation.show_admission_no ? 1 : 0) +
    1 + // Student Name (Fixed)
    (state.settings.tabulation.show_father_name ? 1 : 0) +
    (state.settings.tabulation.show_mother_name ? 1 : 0) +
    1 + // Subjects (Fixed)
    (state.settings.tabulation.show_total_marks ? 1 : 0) +
    (state.settings.tabulation.show_percentage ? 1 : 0) +
    1 + // GPA (Fixed)
    1 + // Grade (Fixed)
    (state.settings.tabulation.show_class_rank ? 1 : 0) +
    (state.settings.tabulation.show_section_rank ? 1 : 0) +
    (state.settings.tabulation.show_remarks ? 1 : 0);

  return (
    <ResponsiveLayout>
      <div className="space-y-6 max-w-7xl mx-auto">
        {/* Header */}
        <div className="bg-gradient-to-r from-indigo-800 via-purple-800 to-pink-800 rounded-xl p-5 shadow-lg">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div className="flex items-center gap-3">
              <div className="h-12 w-12 bg-white/20 rounded-xl flex items-center justify-center">
                <Printer className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-white">Print Settings</h1>
                <p className="text-white/80 text-sm">Configure print layouts for all reports</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <DirtyIndicator isDirty={state.isDirty} />
              <Button onClick={resetToDefault} variant="secondary" className="bg-white/20 hover:bg-white/30 text-white border-0">
                <RotateCcw className="mr-2 h-4 w-4" />
                Reset
              </Button>
              <Button onClick={() => saveSettings(false)} disabled={state.saving} className="bg-emerald-600 hover:bg-emerald-700 text-white">
                {state.saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
                Save
              </Button>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-5">
          <TabsList className="grid grid-cols-4 gap-2 bg-gray-100 dark:bg-gray-800 p-1 rounded-xl">
            <TabsTrigger value="tabulation" className="rounded-lg data-[state=active]:bg-indigo-600 data-[state=active]:text-white">
              <FileText className="h-4 w-4 mr-2" />
              Tabulation
            </TabsTrigger>
            <TabsTrigger value="progress-card" className="rounded-lg data-[state=active]:bg-indigo-600 data-[state=active]:text-white">
              <GraduationCap className="h-4 w-4 mr-2" />
              Progress Card
            </TabsTrigger>
            <TabsTrigger value="certificate" className="rounded-lg data-[state=active]:bg-indigo-600 data-[state=active]:text-white">
              <Award className="h-4 w-4 mr-2" />
              Certificate
            </TabsTrigger>
            <TabsTrigger value="common" className="rounded-lg data-[state=active]:bg-indigo-600 data-[state=active]:text-white">
              <Settings className="h-4 w-4 mr-2" />
              Common
            </TabsTrigger>
          </TabsList>

          {/* ============================================ */}
          {/* TABULATION TAB */}
          {/* ============================================ */}
          <TabsContent value="tabulation" className="space-y-5">
            <Card className="border-0 shadow-lg bg-white dark:bg-gray-900">
              <CardHeader className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-950/30 dark:to-indigo-950/30 rounded-t-xl">
                <div className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                  <CardTitle className="text-gray-900 dark:text-white">Tabulation Sheet Settings</CardTitle>
                </div>
                <CardDescription className="text-gray-600 dark:text-gray-400">
                  Configure which columns to show in tabulation sheet. Toggle switches below to show/hide columns.
                </CardDescription>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                {/* Column Visibility */}
                <div>
                  <Label className="text-sm font-semibold mb-3 block text-gray-700 dark:text-gray-300">
                    📋 Column Visibility (Toggle to Show/Hide)
                  </Label>
                  <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                    <ColorCodedSwitch
                      label="SL"
                      description="Serial Number"
                      checked={state.settings.tabulation.show_serial}
                      onChange={(v) => updateTabulation('show_serial', v)}
                      color="blue"
                      icon={<Hash className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Photo"
                      description="Student Photo"
                      checked={state.settings.tabulation.show_photo}
                      onChange={(v) => updateTabulation('show_photo', v)}
                      color="blue"
                      icon={<ImageIcon className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Roll"
                      description="Roll Number"
                      checked={state.settings.tabulation.show_roll}
                      onChange={(v) => updateTabulation('show_roll', v)}
                      color="blue"
                      icon={<Hash className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Admission No"
                      description="Admission Number"
                      checked={state.settings.tabulation.show_admission_no}
                      onChange={(v) => updateTabulation('show_admission_no', v)}
                      color="blue"
                      icon={<Hash className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Student Name"
                      description="Student's Full Name"
                      checked={true}
                      onChange={() => {}}
                      color="green"
                      icon={<User className="h-3.5 w-3.5" />}
                      isFixed={true}
                    />
                    <ColorCodedSwitch
                      label="Father's Name"
                      description="Father/Guardian Name"
                      checked={state.settings.tabulation.show_father_name}
                      onChange={(v) => updateTabulation('show_father_name', v)}
                      color="green"
                      icon={<Users className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Mother's Name"
                      description="Mother's Name"
                      checked={state.settings.tabulation.show_mother_name}
                      onChange={(v) => updateTabulation('show_mother_name', v)}
                      color="green"
                      icon={<Users className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Subjects"
                      description="Subject-wise Marks"
                      checked={true}
                      onChange={() => {}}
                      color="purple"
                      icon={<BookOpen className="h-3.5 w-3.5" />}
                      isFixed={true}
                    />
                    <ColorCodedSwitch
                      label="Total Marks"
                      description="Sum of all subjects"
                      checked={state.settings.tabulation.show_total_marks}
                      onChange={(v) => updateTabulation('show_total_marks', v)}
                      color="amber"
                      icon={<BarChart3 className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Percentage"
                      description="% of total marks"
                      checked={state.settings.tabulation.show_percentage}
                      onChange={(v) => updateTabulation('show_percentage', v)}
                      color="amber"
                      icon={<BarChart3 className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="GPA"
                      description="Grade Point Average"
                      checked={true}
                      onChange={() => {}}
                      color="amber"
                      icon={<BarChart3 className="h-3.5 w-3.5" />}
                      isFixed={true}
                    />
                    <ColorCodedSwitch
                      label="Grade"
                      description="Letter Grade (A+, A, B...)"
                      checked={true}
                      onChange={() => {}}
                      color="amber"
                      icon={<Award className="h-3.5 w-3.5" />}
                      isFixed={true}
                    />
                    <ColorCodedSwitch
                      label="Class Rank"
                      description="Position in Class"
                      checked={state.settings.tabulation.show_class_rank}
                      onChange={(v) => updateTabulation('show_class_rank', v)}
                      color="orange"
                      icon={<Trophy className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Section Rank"
                      description="Position in Section"
                      checked={state.settings.tabulation.show_section_rank}
                      onChange={(v) => updateTabulation('show_section_rank', v)}
                      color="orange"
                      icon={<Trophy className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Remarks"
                      description="Additional Comments"
                      checked={state.settings.tabulation.show_remarks}
                      onChange={(v) => updateTabulation('show_remarks', v)}
                      color="gray"
                      icon={<AlertCircle className="h-3.5 w-3.5" />}
                    />
                  </div>
                </div>

                <Separator className="bg-gray-200 dark:bg-gray-700" />

                {/* Print Layout */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">📄 Paper Size</Label>
                    <Select value={state.settings.tabulation.paper_size} onValueChange={(v: TabulationSettings['paper_size']) => updateTabulation('paper_size', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="A4">A4 (210 x 297 mm)</SelectItem>
                        <SelectItem value="Letter">Letter (216 x 279 mm)</SelectItem>
                        <SelectItem value="Legal">Legal (216 x 356 mm)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">🔄 Orientation</Label>
                    <Select value={state.settings.tabulation.orientation} onValueChange={(v: TabulationSettings['orientation']) => updateTabulation('orientation', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="portrait">Portrait</SelectItem>
                        <SelectItem value="landscape">Landscape</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">🔤 Font Size</Label>
                    <Select value={state.settings.tabulation.font_size} onValueChange={(v: TabulationSettings['font_size']) => updateTabulation('font_size', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="small">Small</SelectItem>
                        <SelectItem value="normal">Normal</SelectItem>
                        <SelectItem value="large">Large</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {/* Preview Configuration - BLACK TEXT for normal mode */}
                <div className="bg-gradient-to-r from-blue-100 via-indigo-100 to-purple-100 dark:from-blue-950/30 dark:via-indigo-950/30 dark:to-purple-950/30 rounded-lg p-4 border border-blue-300 dark:border-blue-800">
                  <div className="flex items-center gap-2 mb-3">
                    <Eye className="h-4 w-4 text-gray-700 dark:text-blue-400" />
                    <span className="text-sm font-semibold text-gray-900 dark:text-blue-300">Preview Configuration</span>
                    <Badge variant="secondary" className="text-xs bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300">Live Preview</Badge>
                  </div>
                  
                  {/* Column Order Display - ALL BLACK TEXT */}
                  <div className="flex flex-wrap gap-2 items-center">
                    {state.settings.tabulation.show_serial && (
                      <Badge className="bg-blue-100 text-gray-900 dark:bg-blue-900/50 dark:text-gray-100 border border-blue-200 dark:border-blue-700 px-3 py-1.5">
                        <span className="font-mono">01</span> SL
                      </Badge>
                    )}
                    {state.settings.tabulation.show_photo && (
                      <Badge className="bg-teal-100 text-gray-900 dark:bg-teal-900/50 dark:text-gray-100 border border-teal-200 dark:border-teal-700 px-3 py-1.5">
                        📷 Photo
                      </Badge>
                    )}
                    {state.settings.tabulation.show_roll && (
                      <Badge className="bg-cyan-100 text-gray-900 dark:bg-cyan-900/50 dark:text-gray-100 border border-cyan-200 dark:border-cyan-700 px-3 py-1.5">
                        # Roll
                      </Badge>
                    )}
                    {state.settings.tabulation.show_admission_no && (
                      <Badge className="bg-sky-100 text-gray-900 dark:bg-sky-900/50 dark:text-gray-100 border border-sky-200 dark:border-sky-700 px-3 py-1.5">
                        🆔 Admission No
                      </Badge>
                    )}
                    <Badge className="bg-green-100 text-gray-900 dark:bg-green-900/50 dark:text-gray-100 border border-green-200 dark:border-green-700 px-3 py-1.5 font-semibold">
                      👤 Student Name
                    </Badge>
                    {state.settings.tabulation.show_father_name && (
                      <Badge className="bg-emerald-100 text-gray-900 dark:bg-emerald-900/50 dark:text-gray-100 border border-emerald-200 dark:border-emerald-700 px-3 py-1.5">
                        👨 Father's Name
                      </Badge>
                    )}
                    {state.settings.tabulation.show_mother_name && (
                      <Badge className="bg-teal-100 text-gray-900 dark:bg-teal-900/50 dark:text-gray-100 border border-teal-200 dark:border-teal-700 px-3 py-1.5">
                        👩 Mother's Name
                      </Badge>
                    )}
                    <Badge className="bg-purple-100 text-gray-900 dark:bg-purple-900/50 dark:text-gray-100 border border-purple-200 dark:border-purple-700 px-3 py-1.5 font-semibold">
                      📚 Subjects
                    </Badge>
                    {state.settings.tabulation.show_total_marks && (
                      <Badge className="bg-amber-100 text-gray-900 dark:bg-amber-900/50 dark:text-gray-100 border border-amber-200 dark:border-amber-700 px-3 py-1.5">
                        📊 Total
                      </Badge>
                    )}
                    {state.settings.tabulation.show_percentage && (
                      <Badge className="bg-yellow-100 text-gray-900 dark:bg-yellow-900/50 dark:text-gray-100 border border-yellow-200 dark:border-yellow-700 px-3 py-1.5">
                        📈 %
                      </Badge>
                    )}
                    <Badge className="bg-orange-100 text-gray-900 dark:bg-orange-900/50 dark:text-gray-100 border border-orange-200 dark:border-orange-700 px-3 py-1.5 font-semibold">
                      📊 GPA
                    </Badge>
                    <Badge className="bg-red-100 text-gray-900 dark:bg-red-900/50 dark:text-gray-100 border border-red-200 dark:border-red-700 px-3 py-1.5 font-semibold">
                      🎯 Grade
                    </Badge>
                    {state.settings.tabulation.show_class_rank && (
                      <Badge className="bg-indigo-100 text-gray-900 dark:bg-indigo-900/50 dark:text-gray-100 border border-indigo-200 dark:border-indigo-700 px-3 py-1.5 font-semibold">
                        🏆 Class Rank
                      </Badge>
                    )}
                    {state.settings.tabulation.show_section_rank && (
                      <Badge className="bg-violet-100 text-gray-900 dark:bg-violet-900/50 dark:text-gray-100 border border-violet-200 dark:border-violet-700 px-3 py-1.5 font-semibold">
                        📌 Section Rank
                      </Badge>
                    )}
                    {state.settings.tabulation.show_remarks && (
                      <Badge className="bg-gray-100 text-gray-900 dark:bg-gray-800 dark:text-gray-100 border border-gray-200 dark:border-gray-600 px-3 py-1.5">
                        💬 Remarks
                      </Badge>
                    )}
                  </div>
                  
                  <div className="flex items-center justify-center gap-1 mt-3 text-xs text-gray-600 dark:text-gray-400">
                    <ChevronRight className="h-3 w-3" />
                    <span>Columns will appear in this order from left to right</span>
                    <ChevronRight className="h-3 w-3" />
                  </div>
                  
                  <div className="mt-3 pt-2 border-t border-blue-300 dark:border-blue-700">
                    <div className="flex flex-wrap gap-3 text-xs">
                      <span className="text-gray-700 dark:text-gray-400">
                        📊 Total Columns: {tabulationColumnCount}
                      </span>
                      <span className="text-gray-700 dark:text-blue-400">🔵 Basic Info</span>
                      <span className="text-gray-700 dark:text-green-400">🟢 Student Info</span>
                      <span className="text-gray-700 dark:text-purple-400">🟣 Academic</span>
                      <span className="text-gray-700 dark:text-amber-400">🟡 Marks</span>
                      <span className="text-gray-700 dark:text-orange-400">🟠 Ranking</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* ============================================ */}
          {/* PROGRESS CARD TAB */}
          {/* ============================================ */}
          <TabsContent value="progress-card" className="space-y-5">
            <Card className="border-0 shadow-lg bg-white dark:bg-gray-900">
              <CardHeader className="bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-950/30 dark:to-emerald-950/30 rounded-t-xl">
                <div className="flex items-center gap-2">
                  <GraduationCap className="h-5 w-5 text-green-600 dark:text-green-400" />
                  <CardTitle className="text-gray-900 dark:text-white">Progress Card Settings</CardTitle>
                </div>
                <CardDescription className="text-gray-600 dark:text-gray-400">
                  Configure student progress card layout and appearance
                </CardDescription>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                <div>
                  <Label className="text-sm font-semibold mb-3 block text-gray-700 dark:text-gray-300">
                    📋 Display Options
                  </Label>
                  <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                    <ColorCodedSwitch
                      label="Student Photo"
                      description="Display student photograph"
                      checked={state.settings.progress_card.show_photo}
                      onChange={(v) => updateProgressCard('show_photo', v)}
                      color="teal"
                      icon={<ImageIcon className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Signature"
                      description="Show teacher/principal signature"
                      checked={state.settings.progress_card.show_signature}
                      onChange={(v) => updateProgressCard('show_signature', v)}
                      color="purple"
                      icon={<Award className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="School Seal"
                      description="Show school seal/stamp"
                      checked={state.settings.progress_card.show_seal}
                      onChange={(v) => updateProgressCard('show_seal', v)}
                      color="purple"
                      icon={<Award className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Grade Distribution"
                      description="Show grade distribution chart"
                      checked={state.settings.progress_card.show_grade_distribution}
                      onChange={(v) => updateProgressCard('show_grade_distribution', v)}
                      color="amber"
                      icon={<BarChart3 className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Attendance Summary"
                      description="Show attendance summary"
                      checked={state.settings.progress_card.show_attendance_summary}
                      onChange={(v) => updateProgressCard('show_attendance_summary', v)}
                      color="blue"
                      icon={<Calendar className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Rank Position"
                      description="Show class/section rank"
                      checked={state.settings.progress_card.show_rank}
                      onChange={(v) => updateProgressCard('show_rank', v)}
                      color="orange"
                      icon={<Trophy className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Student Address"
                      description="Show student address"
                      checked={state.settings.progress_card.show_address}
                      onChange={(v) => updateProgressCard('show_address', v)}
                      color="gray"
                      icon={<MapPin className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Parent Contact"
                      description="Show parent phone/email"
                      checked={state.settings.progress_card.show_parent_contact}
                      onChange={(v) => updateProgressCard('show_parent_contact', v)}
                      color="gray"
                      icon={<Phone className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Date of Birth"
                      description="Show student DOB"
                      checked={state.settings.progress_card.show_dob}
                      onChange={(v) => updateProgressCard('show_dob', v)}
                      color="gray"
                      icon={<Calendar className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Admission Date"
                      description="Show admission date"
                      checked={state.settings.progress_card.show_admission_date}
                      onChange={(v) => updateProgressCard('show_admission_date', v)}
                      color="gray"
                      icon={<Calendar className="h-3.5 w-3.5" />}
                    />
                    <ColorCodedSwitch
                      label="Include All Terms"
                      description="Show all terms in one card"
                      checked={state.settings.progress_card.include_all_terms}
                      onChange={(v) => updateProgressCard('include_all_terms', v)}
                      color="purple"
                      icon={<BookOpen className="h-3.5 w-3.5" />}
                    />
                  </div>
                </div>

                <Separator className="bg-gray-200 dark:bg-gray-700" />

                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">📄 Paper Size</Label>
                    <Select value={state.settings.progress_card.paper_size} onValueChange={(v: ProgressCardSettings['paper_size']) => updateProgressCard('paper_size', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="A4">A4 (210 x 297 mm)</SelectItem>
                        <SelectItem value="Letter">Letter (216 x 279 mm)</SelectItem>
                        <SelectItem value="Legal">Legal (216 x 356 mm)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">🔄 Orientation</Label>
                    <Select value={state.settings.progress_card.orientation} onValueChange={(v: ProgressCardSettings['orientation']) => updateProgressCard('orientation', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="portrait">Portrait</SelectItem>
                        <SelectItem value="landscape">Landscape</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {/* Preview Section - BLACK TEXT */}
                <div className="bg-gradient-to-r from-green-100 to-emerald-100 dark:from-green-950/30 dark:to-emerald-950/30 rounded-lg p-4 border border-green-300 dark:border-green-800">
                  <div className="flex items-center gap-2 mb-3">
                    <Eye className="h-4 w-4 text-gray-700 dark:text-green-400" />
                    <span className="text-sm font-semibold text-gray-900 dark:text-green-300">Preview Configuration</span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {state.settings.progress_card.show_photo && <Badge className="bg-teal-100 text-gray-900 dark:bg-teal-900/50 dark:text-gray-100 border border-teal-200 dark:border-teal-700">📷 Photo</Badge>}
                    {state.settings.progress_card.show_signature && <Badge className="bg-purple-100 text-gray-900 dark:bg-purple-900/50 dark:text-gray-100 border border-purple-200 dark:border-purple-700">✍️ Signature</Badge>}
                    {state.settings.progress_card.show_seal && <Badge className="bg-purple-100 text-gray-900 dark:bg-purple-900/50 dark:text-gray-100 border border-purple-200 dark:border-purple-700">🖨️ Seal</Badge>}
                    {state.settings.progress_card.show_grade_distribution && <Badge className="bg-amber-100 text-gray-900 dark:bg-amber-900/50 dark:text-gray-100 border border-amber-200 dark:border-amber-700">📊 Grade Distribution</Badge>}
                    {state.settings.progress_card.show_attendance_summary && <Badge className="bg-blue-100 text-gray-900 dark:bg-blue-900/50 dark:text-gray-100 border border-blue-200 dark:border-blue-700">📅 Attendance</Badge>}
                    {state.settings.progress_card.show_rank && <Badge className="bg-orange-100 text-gray-900 dark:bg-orange-900/50 dark:text-gray-100 border border-orange-200 dark:border-orange-700">🏆 Rank</Badge>}
                    {state.settings.progress_card.include_all_terms && <Badge className="bg-purple-100 text-gray-900 dark:bg-purple-900/50 dark:text-gray-100 border border-purple-200 dark:border-purple-700">📚 All Terms</Badge>}
                  </div>
                  <p className="text-xs text-gray-700 dark:text-green-400 mt-2">
                    Paper: {state.settings.progress_card.paper_size} | Orientation: {state.settings.progress_card.orientation}
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* ============================================ */}
          {/* CERTIFICATE TAB */}
          {/* ============================================ */}
          <TabsContent value="certificate" className="space-y-5">
            <Card className="border-0 shadow-lg bg-white dark:bg-gray-900">
              <CardHeader className="bg-gradient-to-r from-amber-50 to-yellow-50 dark:from-amber-950/30 dark:to-yellow-950/30 rounded-t-xl">
                <div className="flex items-center gap-2">
                  <Award className="h-5 w-5 text-amber-600 dark:text-amber-400" />
                  <CardTitle className="text-gray-900 dark:text-white">Certificate Settings</CardTitle>
                </div>
                <CardDescription className="text-gray-600 dark:text-gray-400">
                  Configure certificate appearance and layout
                </CardDescription>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                  <ColorCodedSwitch
                    label="Border"
                    description="Show certificate border"
                    checked={state.settings.certificate.show_border}
                    onChange={(v) => updateCertificate('show_border', v)}
                    color="amber"
                    icon={<Award className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="School Seal"
                    description="Show school seal"
                    checked={state.settings.certificate.show_seal}
                    onChange={(v) => updateCertificate('show_seal', v)}
                    color="purple"
                    icon={<Award className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="Signature"
                    description="Show signatures"
                    checked={state.settings.certificate.show_signature}
                    onChange={(v) => updateCertificate('show_signature', v)}
                    color="purple"
                    icon={<Award className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="Background Pattern"
                    description="Show decorative pattern"
                    checked={state.settings.certificate.background_pattern}
                    onChange={(v) => updateCertificate('background_pattern', v)}
                    color="gray"
                    icon={<Award className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="Achievement Details"
                    description="Show achievement text"
                    checked={state.settings.certificate.show_achievement_details}
                    onChange={(v) => updateCertificate('show_achievement_details', v)}
                    color="blue"
                    icon={<Award className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="Date"
                    description="Show certificate date"
                    checked={state.settings.certificate.show_date}
                    onChange={(v) => updateCertificate('show_date', v)}
                    color="gray"
                    icon={<Calendar className="h-3.5 w-3.5" />}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Border Color</Label>
                    <div className="flex gap-2">
                      <Input 
                        type="color" 
                        value={state.settings.certificate.border_color}
                        onChange={(e) => updateCertificate('border_color', e.target.value)}
                        className="w-16 h-10 p-1"
                      />
                      <Input 
                        type="text" 
                        value={state.settings.certificate.border_color}
                        onChange={(e) => updateCertificate('border_color', e.target.value)}
                        className="flex-1 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                      />
                    </div>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Border Width (px)</Label>
                    <Input 
                      type="number" 
                      value={state.settings.certificate.border_width}
                      onChange={(e) => updateCertificate('border_width', parseInt(e.target.value) || 2)}
                      min={1}
                      max={10}
                      className="bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                    />
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Paper Size</Label>
                    <Select value={state.settings.certificate.paper_size} onValueChange={(v: CertificateSettings['paper_size']) => updateCertificate('paper_size', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="A4">A4 (210 x 297 mm)</SelectItem>
                        <SelectItem value="Letter">Letter (216 x 279 mm)</SelectItem>
                        <SelectItem value="Legal">Legal (216 x 356 mm)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Orientation</Label>
                    <Select value={state.settings.certificate.orientation} onValueChange={(v: CertificateSettings['orientation']) => updateCertificate('orientation', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="portrait">Portrait</SelectItem>
                        <SelectItem value="landscape">Landscape</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Font Style</Label>
                    <Select value={state.settings.certificate.font_family} onValueChange={(v: CertificateSettings['font_family']) => updateCertificate('font_family', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="default">Default (Arial)</SelectItem>
                        <SelectItem value="serif">Serif (Times New Roman)</SelectItem>
                        <SelectItem value="handwriting">Handwriting (Cursive)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {/* Preview - BLACK TEXT */}
                <div 
                  className="bg-amber-100 dark:bg-amber-950/30 rounded-lg p-4 text-center border border-amber-300 dark:border-amber-800"
                  style={{ 
                    borderColor: state.settings.certificate.border_color, 
                    borderWidth: state.settings.certificate.show_border ? `${state.settings.certificate.border_width}px` : '0px', 
                    borderStyle: 'solid' 
                  }}
                >
                  <p className="text-sm text-gray-900 dark:text-amber-300">Certificate Preview</p>
                  <p className="text-xs text-gray-700 dark:text-gray-400 mt-1">
                    Border: {state.settings.certificate.show_border ? 'Yes' : 'No'} | 
                    Paper: {state.settings.certificate.paper_size} | 
                    Orientation: {state.settings.certificate.orientation}
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* ============================================ */}
          {/* COMMON TAB */}
          {/* ============================================ */}
          <TabsContent value="common" className="space-y-5">
            <Card className="border-0 shadow-lg bg-white dark:bg-gray-900">
              <CardHeader className="bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-950/30 dark:to-pink-950/30 rounded-t-xl">
                <div className="flex items-center gap-2">
                  <Settings className="h-5 w-5 text-purple-600 dark:text-purple-400" />
                  <CardTitle className="text-gray-900 dark:text-white">Common Print Settings</CardTitle>
                </div>
                <CardDescription className="text-gray-600 dark:text-gray-400">
                  Global settings for all print outputs
                </CardDescription>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                  <ColorCodedSwitch
                    label="Logo Position"
                    description="Logo alignment on header"
                    checked={state.settings.common.logo_position === 'left'}
                    onChange={(v) => updateCommon('logo_position', v ? 'left' : 'center')}
                    color="purple"
                    icon={<ImageIcon className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="Generated Date"
                    description="Show generation date"
                    checked={state.settings.common.show_generated_date}
                    onChange={(v) => updateCommon('show_generated_date', v)}
                    color="gray"
                    icon={<Calendar className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="Page Numbers"
                    description="Show page numbers"
                    checked={state.settings.common.show_page_numbers}
                    onChange={(v) => updateCommon('show_page_numbers', v)}
                    color="gray"
                    icon={<Hash className="h-3.5 w-3.5" />}
                  />
                  <ColorCodedSwitch
                    label="QR Code"
                    description="Show QR code on reports"
                    checked={state.settings.common.show_qr_code}
                    onChange={(v) => updateCommon('show_qr_code', v)}
                    color="teal"
                    icon={<Award className="h-3.5 w-3.5" />}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Logo Position</Label>
                    <Select value={state.settings.common.logo_position} onValueChange={(v: CommonSettings['logo_position']) => updateCommon('logo_position', v)}>
                      <SelectTrigger className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="left">Left</SelectItem>
                        <SelectItem value="center">Center</SelectItem>
                        <SelectItem value="right">Right</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Primary Color</Label>
                    <div className="flex gap-2">
                      <Input 
                        type="color" 
                        value={state.settings.common.primary_color}
                        onChange={(e) => updateCommon('primary_color', e.target.value)}
                        className="w-16 h-10 p-1"
                      />
                      <Input 
                        type="text" 
                        value={state.settings.common.primary_color}
                        onChange={(e) => updateCommon('primary_color', e.target.value)}
                        className="flex-1 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                      />
                    </div>
                  </div>
                  <div>
                    <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Secondary Color</Label>
                    <div className="flex gap-2">
                      <Input 
                        type="color" 
                        value={state.settings.common.secondary_color}
                        onChange={(e) => updateCommon('secondary_color', e.target.value)}
                        className="w-16 h-10 p-1"
                      />
                      <Input 
                        type="text" 
                        value={state.settings.common.secondary_color}
                        onChange={(e) => updateCommon('secondary_color', e.target.value)}
                        className="flex-1 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                      />
                    </div>
                  </div>
                </div>

                <div>
                  <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Header Text</Label>
                  <Input 
                    value={state.settings.common.header_text}
                    onChange={(e) => updateCommon('header_text', e.target.value)}
                    className="bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                    placeholder="Enter header text (optional)"
                  />
                </div>

                <div>
                  <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Footer Text</Label>
                  <Input 
                    value={state.settings.common.footer_text}
                    onChange={(e) => updateCommon('footer_text', e.target.value)}
                    className="bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                    placeholder="Enter footer text"
                  />
                </div>

                <Separator className="bg-gray-200 dark:bg-gray-700" />

                <div>
                  <div className="flex items-center justify-between mb-4">
                    <Label className="text-sm font-semibold text-gray-700 dark:text-gray-300">💧 Watermark Settings</Label>
                    <Switch checked={state.settings.common.watermark_enabled} onCheckedChange={(v) => updateCommon('watermark_enabled', v)} />
                  </div>
                  {state.settings.common.watermark_enabled && (
                    <div>
                      <Label className="text-sm font-semibold mb-2 block text-gray-700 dark:text-gray-300">Watermark Text</Label>
                      <Input 
                        value={state.settings.common.watermark_text}
                        onChange={(e) => updateCommon('watermark_text', e.target.value)}
                        className="bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                        placeholder="Enter watermark text"
                      />
                    </div>
                  )}
                </div>

                {/* School Info Preview - BLACK TEXT */}
                <div className="bg-gray-100 dark:bg-gray-800/50 rounded-lg p-4 border border-gray-200 dark:border-gray-700">
                  <div className="flex items-center gap-2 mb-2">
                    <CheckCircle className="h-4 w-4 text-green-600 dark:text-green-400" />
                    <span className="text-sm font-medium text-gray-900 dark:text-gray-300">School Information (from settings)</span>
                  </div>
                  <div className="text-sm text-gray-700 dark:text-gray-400">
                    <p><strong>School Name:</strong> {state.schoolInfo?.school_name || 'Not set'}</p>
                    <p><strong>Address:</strong> {state.schoolInfo?.school_address || 'Not set'}</p>
                    <p><strong>Phone:</strong> {state.schoolInfo?.school_phone || 'Not set'}</p>
                    <p><strong>Email:</strong> {state.schoolInfo?.school_email || 'Not set'}</p>
                  </div>
                  <p className="text-xs text-gray-600 dark:text-gray-500 mt-2">
                    These values are from School Settings. To change them, go to Settings → School Settings.
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Footer Note */}
        <div className="text-center text-xs text-gray-500 dark:text-gray-400 py-4">
          <p>These settings apply to all exam reports: Tabulation Sheet, Progress Card, Certificate, and Merit List</p>
        </div>
      </div>
    </ResponsiveLayout>
  );
}
